# Generated by Django 5.2.3 on 2025-06-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='login_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
