# Generated by Django 5.2.3 on 2025-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useractivity_login_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
