# Generated by Django 5.2.3 on 2025-06-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_avaliable_orderproductonline_email_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestlogs', to='products.category'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestlogs', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestlogs', to='products.producttype'),
        ),
    ]
