# Generated by Django 5.2.3 on 2025-06-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderproductonline',
            name='created_at',
        ),
        migrations.AddField(
            model_name='orderproductonline',
            name='address',
            field=models.TextField(default=1, help_text='Full address of requester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproductonline',
            name='name',
            field=models.CharField(default=1, help_text='Person requesting', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproductonline',
            name='number',
            field=models.CharField(default=1, help_text='Contact number', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
    ]
