# Generated by Django 5.2.3 on 2025-06-19 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_attachmentdownloadlog_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderproductonline',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='color',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='size',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='orderproductonline',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
